name: Navegador Visual Ultra Rapido con Audio

on:
  workflow_dispatch:

jobs:
  run-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar base del repositorio
        uses: actions/checkout@v4

      - name: Encender Navegador con Audio e Iniciar Tunel Camuflado
        run: |
          # 1. Encendemos un navegador de alta velocidad (Kasm Web Chromium) con Audio integrado en solo 3 segundos
          docker run -d --name navegador -p 8080:6901 --shm-size=512m -e VNC_PW=password kasmweb/chromium:1.15.0
          sleep 5
          
          # 2. Descargamos la herramienta de Cloudflare directamente
          wget -q https://github.com
          chmod +x cloudflared-linux-amd64
          
          # 3. Lanzamos el puente invisible directo hacia el navegador con audio
          ./cloudflared-linux-amd64 tunnel --url http://localhost:8080
