name: Navegador Visual Ultra Rapido con Audio

on:
  workflow_dispatch:

jobs:
  run-browser:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar base del repositorio
        uses: actions/checkout@v4

      - name: Encender Navegador con Audio e Iniciar Tunel Camuflado
        run: |
          # 1. Encendemos el contenedor con el tag universal optimizado para servidores en la nube
          docker run -d --name navegador -p 8080:6901 --shm-size=512m -e VNC_PW=password kasmweb/chromium:1.15.0-rolling
          sleep 5
          
          # 2. Descargamos Cloudflare usando su canal principal de alta velocidad
          curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          
          # 3. Lanzamos el puente invisible directo hacia el navegador con audio
          ./cloudflared tunnel --url http://localhost:8080
