name: Terminal Invisible Ultra Anti Bloqueos

on:
  workflow_dispatch:

jobs:
  run-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar base
        uses: actions/checkout@v4

      - name: Instalar Terminal Web y Cloudflared
        run: |
          sudo apt-get update
          # Instalamos la terminal web ligera ttyd
          sudo apt-get install -y ttyd
          # Descargamos el agente oficial de tuneles de Cloudflare
          curl -L --output cloudflared.deb https://github.com
          sudo dpkg -i cloudflared.deb

      - name: Encender Terminal e Iniciar Tunel Camuflado
        run: |
          # 1. Activamos la terminal en segundo plano en el puerto 8080
          ttyd -p 8080 bash &
          
          # 2. Creamos un tunel público instantaneo y camuflado de Cloudflare
          cloudflared tunnel --url http://localhost:8080
